CREATE TABLE IF NOT EXISTS rules (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	type TEXT NOT NULL,
	value TEXT NOT NULL,
	action TEXT NOT NULL,
	protocol TEXT,
	port INTEGER,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);