CREATE TABLE IF NOT EXISTS rules (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	policy_id INTEGER NOT NULL REFERENCES policies(id) ON DELETE CASCADE,
	type TEXT NOT NULL,
	value TEXT NOT NULL,
	protocol TEXT,
	port INTEGER,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
